<a href="https://colab.research.google.com/github/saaraf1235-bot/NumPY_Session13-_Assignment13/blob/main/Session_13t_Assignment_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q.1 (Basic Array Creation)

In [ ]:
#a) code:
import numpy as np
arr = np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [ ]:
print("Shape:",arr.shape)
print("Datatype: ",arr.dtype)

Shape: (5,)
Datatype:  int64


In [ ]:
#b) code:
arr_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_1)
print("Shape:",arr_1.shape)
print("Datatype:",arr_1.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Datatype: int64


Q.2 (np.zeros() and np.ones())

In [ ]:
#a) code:
arr = np.zeros(8)
print("One dimensional array: ",arr)
print("Shape: ",arr.shape)

One dimensional array:  [0. 0. 0. 0. 0. 0. 0. 0.]
Shape:  (8,)


In [ ]:
#b) code:
arr_2d = np.ones((4,4))
print("array: ",arr_2d)
print("Shape: ",arr_2d.shape)

array:  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Shape:  (4, 4)


In [ ]:
#c) code:
arr_3d = np.zeros((3,3))
print("array:",arr_3d)
print("Shape:",arr_3d.shape)

array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape: (3, 3)


Q.3 (np.arange())

In [ ]:
#a) code:
arr = np.arange(0,21,1)
print("Numbers from 0 to 21:",arr)

#b) code:
arr_e = np.arange(0,51,2)
print("Even numbers between 0 to 50:",arr_e)

#c) code:
arr_s = np.arange(5,100,5)
print("Numbers from 5 to 100 with steps of 5:",arr_s)

Numbers from 0 to 21: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even numbers between 0 to 50: [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]
Numbers from 5 to 100 with steps of 5: [ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


Q.4 (np.linspace())

In [ ]:
#a) code:
arr_eq = np.linspace(0,5,10)
print("10 equally spaced numbers between 0 and 5:",arr_eq)
print("Length:",len(arr_eq))
print("\n")


#b) code:
arr_eq1 = np.linspace(-10,10,15)
print("15 equally spaced numbers between -10 and 10:",arr_eq1)
print("Length:",len(arr_eq1))


10 equally spaced numbers between 0 and 5: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length: 10


15 equally spaced numbers between -10 and 10: [-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length: 15


Q.5 (Random arrays)

In [ ]:
#a) code:
arr_random = np.random.rand(10)
print("1D array of 10 Random numbers between 0 and 1:",arr_random)
print("Shape:",arr_random.shape)
print("\n")

#b) code:
arr_random1 = np.random.randn(3,3)
print("3x3 matrix of random numbers from standard normal distribution:",arr_random1)
print("Shape:",arr_random1.shape)
print("\n")

#c) code:
arr_randint = np.random.randint(10,51,size = (4,5))
print("2D array of (4x5) of random integers between 10 and 51:",arr_randint)
print("Shape:",arr_randint.shape)

1D array of 10 Random numbers between 0 and 1: [0.20702283 0.01490274 0.54616291 0.61989501 0.6985141  0.93641208
 0.50927891 0.40401688 0.17212218 0.22113972]
Shape: (10,)


3x3 matrix of random numbers from standard normal distribution: [[-0.26540814 -1.1498829   1.57136847]
 [ 0.17970576  0.45529595  1.44267545]
 [ 1.75113188  0.74019257  0.48455933]]
Shape: (3, 3)


2D array of (4x5) of random integers between 10 and 51: [[45 40 21 38 16]
 [39 39 26 25 36]
 [29 17 36 23 36]
 [13 22 32 48 41]]
Shape: (4, 5)


Q.6 (Vectors and Basic Operations)

In [ ]:
#a)
V1 = np.array([2,4,6,8])
V2 = np.array([1,3,5,7])

print("Vector V1 is:",V1)
print("Vector V2 is:",V2)

add = V1 + V2
print("Addition:",add)
sub = V1 - V2
print("Subtraction:",sub)
element_mul = V1 * V2
print("Element- wise multiplication is:",element_mul)
dot_product = np.dot(V1,V2)
print("Using dot operator multiplication is:",dot_product)

Vector V1 is: [2 4 6 8]
Vector V2 is: [1 3 5 7]
Addition: [ 3  7 11 15]
Subtraction: [1 1 1 1]
Element- wise multiplication is: [ 2 12 30 56]
Using dot operator multiplication is: 100


Q.7 (Matrices and Operations)

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

print("Matrix 1:",A)
print("Matrix 2:",B)

add = A + B
print("Matrix addition is:",add)
mul = A @ B
print("Matrix multilpication is:",mul)
element_mul = A * B
print("Element-wise multilpication is:",element_mul)


Matrix 1: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix 2: [[9 8 7]
 [6 5 4]
 [3 2 1]]
Matrix addition is: [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix multilpication is: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Element-wise multilpication is: [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


Q.8 (Properties of arrays)

In [ ]:
matrics = np.random.randint(1,101,size = (4,4))
print("Matrics is:",matrics)

print("Shape:",matrics.shape)
print("Dimension (ndim):",matrics.ndim)
print("Datatype:",matrics.dtype)
print("Minimum value:",matrics.min())
print("Maximum value:",matrics.max())


Matrics is: [[20 36 74 89]
 [45 65 84 33]
 [38 59 33 65]
 [96 78 45 40]]
Shape: (4, 4)
Dimension (ndim): 2
Datatype: int64
Minimum value: 20
Maximum value: 96


Q.9 (Combined - Random + Reshape + Statistics)

In [ ]:
arr = np.random.randint(1,50,20)
print("Created array:",arr)

arr_1 = arr.reshape(4,5)
print("Reshape 4x5 matrix is:",arr_1)

print("\nStatistics of matrix")
print("Sum:",arr_1.sum())
print("Mean:",arr_1.mean())
print("Standard Deviation:",round(arr_1.std(),2))
max = arr_1.max(axis=1)
print("Maximum value in each row:",max)

Created array: [ 9 14 49  2 11 11 31 48 19  4  3  6 26  7  5  5 35 48  3 44]
Reshape 4x5 matrix is: [[ 9 14 49  2 11]
 [11 31 48 19  4]
 [ 3  6 26  7  5]
 [ 5 35 48  3 44]]

Statistics of matrix
Sum: 380
Mean: 19.0
Standard Deviation: 16.79
Maximum value in each row: [49 48 26 48]


Q.10 (Mini Project - NumPy Application)

In [ ]:
try:
  #ask user how many numbers to generate
  n = int(input("How many numbers do you want to generate?"))
 #check if input is valid
  if n <= 0:
    print("Error: Please enter a valid integer")
  else:
   #generate n random numbers between 10  and 100
    arr = np.random.randint(10,101,size = n)
    #print the array
    print("Array of {n) elements is:",arr)

    #mean,median,standard deviation.minimum value,maximum value = statistics
    print("====Statistics====")
    print("Mean:",round(arr.mean(),2))
    print("Median:",np.median(arr))
    print("Standard Deviation:",round(arr.std(),2))
    print("Minimum :",arr.min())
    print("Maximum:",arr.max())

    #trying to reshaping into 2D array and print row - wise sum
    #check if array can be reshaped into 2D
    reshaped = False

    for rows in range(2,n):
      if rows % n == 0:
        columns = n //rows
        matrics_2d = arr.reshape(rows,columns)
        print("Reshaped matrix:",matrics_2d)

        #row-wise sum: axis=1 means sum alomg rows
        row_sum = matrics_2d.sum(axis=1)
        print("Row_wise sum is:",row_sum)
        reshaped = True
        break

    if not reshaped:
      print(f"Cannot reshape {n} elements into 2D array")
      print("Note: Try even numbers")

except ValueError:
   print("Error:Please enter a valid integer number")
except Exception as e:
   print(f"An unexpected error occured: {e}")



How many numbers do you want to generate?5
Array of {n) elements is: [65 46 62 62 72]
====Statistics====
Mean: 61.4
Median: 62.0
Standard Deviation: 8.52
Minimum : 46
Maximum: 72
Cannot reshape 5 elements into 2D array
Note: Try even numbers
